# Generated by Django 3.2 on 2024-01-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='City name')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.IntegerField(verbose_name='Температура')),
                ('pressure', models.IntegerField(verbose_name='Атмосферное давление')),
                ('wind_speed', models.IntegerField(verbose_name='Скорость ветра')),
                ('last_date', models.DateTimeField(verbose_name='Последнаяя дата запроса')),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_api.city')),
            ],
        ),
    ]
